// Copyright (c) 2016 Fedor Gogolev <knsd@knsd.net>
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

pub const INT: u8 = b'I';
pub const BININT: u8 = b'J';
pub const BININT1: u8 = b'K';
pub const BININT2: u8 = b'M';
pub const LONG: u8 = b'L';
pub const LONG1: u8 = b'\x8a';
pub const LONG4: u8 = b'\x8b';
pub const MARK: u8 = b'(';
pub const STOP: u8 = b'.';
pub const POP: u8 = b'0';
pub const POP_MARK: u8 = b'1';
pub const DUP: u8 = b'2';
pub const FLOAT: u8 = b'F';
pub const BINFLOAT: u8 = b'G';
pub const NONE: u8 = b'N';
pub const PERSID: u8 = b'P';
pub const BINPERSID: u8 = b'Q';
pub const REDUCE: u8 = b'R';
pub const STRING: u8 = b'S';
pub const BINSTRING: u8 = b'T';
pub const SHORT_BINSTRING: u8 = b'U';
pub const UNICODE: u8 = b'V';
pub const BINUNICODE: u8 = b'X';
pub const APPEND: u8 = b'a';
pub const BUILD: u8 = b'b';
pub const GLOBAL: u8 = b'c';
pub const DICT: u8 = b'd';
pub const EMPTY_DICT: u8 = b'}';
pub const APPENDS: u8 = b'e';
pub const GET: u8 = b'g';
pub const BINGET: u8 = b'h';
pub const INST: u8 = b'i';
pub const LONG_BINGET: u8 = b'j';
pub const LIST: u8 = b'l';
pub const EMPTY_LIST: u8 = b']';
pub const OBJ: u8 = b'o';
pub const PUT: u8 = b'p';
pub const BINPUT: u8 = b'q';
pub const LONG_BINPUT: u8 = b'r';
pub const SETITEM: u8 = b's';
pub const TUPLE: u8 = b't';
pub const EMPTY_TUPLE: u8 = b')';
pub const SETITEMS: u8 = b'u';
pub const PROTO: u8 = b'\x80';
pub const NEWOBJ: u8 = b'\x81';
pub const EXT1: u8 = b'\x82';
pub const EXT2: u8 = b'\x83';
pub const EXT4: u8 = b'\x84';
pub const TUPLE1: u8 = b'\x85';
pub const TUPLE2: u8 = b'\x86';
pub const TUPLE3: u8 = b'\x87';
pub const NEWTRUE: u8 = b'\x88';
pub const NEWFALSE: u8 = b'\x89';
